CREATE VIEW PIRATE_LEVELS_VIEW
AS  
SELECT a.LEVEL_ID, a.NAME, s.X as START_X, s.Y as START_Y, max(b.X) as MAX_X, max(b.Y) as MAX_Y
   FROM S1138056.PIRATE_LEVELS a,
   TABLE(SDO_UTIL.GETVERTICES(a.START_POINT)) s,
   TABLE(SDO_UTIL.GETVERTICES(a.BOUNDARY)) b
   GROUP BY a.LEVEL_ID,a.NAME,s.X, s.Y Order by a.LEVEL_ID;
