CREATE TABLE PIRATE_MAPPING
(LEVEL_ID NUMBER (2) NOT NULL,
OBJECT_ID NUMBER (3) NOT NULL,
FOREIGN KEY (LEVEL_ID) REFERENCES PIRATE_LEVELS(LEVEL_ID),
FOREIGN KEY (OBJECT_ID) REFERENCES PIRATE_OBJECTS(OBJECT_ID),
PRIMARY KEY (LEVEL_ID,OBJECT_ID))
/
