INSERT INTO PIRATE_LEVELS VALUES(
		1,
		'TEST',
		MDSYS.SDO_GEOMETRY(
			2001,
			NULL,
			MDSYS.SDO_POINT_TYPE(0.5, 0.5, NULL),
			NULL,
			NULL
		),
		MDSYS.SDO_GEOMETRY(
			2003,
			NULL,
			NULL,
			MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 3),
			MDSYS.SDO_ORDINATE_ARRAY(0,0,10,10)
		)
	)
	/