CREATE TABLE PIRATE_OBJECTS
(OBJECT_ID NUMBER (3) NOT NULL,
OBJECT MDSYS.SDO_GEOMETRY,
TYPE_ID NUMBER (2),
FILL_ID NUMBER (3),
PRIMARY KEY(OBJECT_ID),
FOREIGN KEY(FILL_ID) REFERENCES PIRATE_FILL(FILL_ID))
/
